#!/usr/bin/env bun
/**
 * Fetch the Google Fonts CSS for the families used by this site,
 * download all referenced WOFF2 files into static/fonts/, and emit
 * a local stylesheet (static/fonts/fonts.css) with @font-face rules
 * pointing at those local files.
 *
 * Run: `bun run scripts/download-fonts.ts`
 *
 * Both JetBrains Mono and Noto Sans JP are licensed under the SIL
 * Open Font License 1.1, which permits self-hosting. License files
 * live at static/fonts/<family>/OFL.txt.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const STATIC_FONTS = join(ROOT, "static", "fonts");
const FONTS_CSS_OUT = join(STATIC_FONTS, "fonts.css");

const GOOGLE_FONTS_URL =
	"https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&family=Noto+Sans+JP:wght@400;700&display=swap";
const UA =
	"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36";

type FontFace = {
	family: string;
	weight: string;
	srcUrl: string;
	localPath: string;
	unicodeRange: string;
};

const familySlug = (family: string) =>
	family.toLowerCase().replace(/['"]/g, "").replaceAll(" ", "-");

function parseFontFaces(css: string): FontFace[] {
	const faces: FontFace[] = [];
	const blockRe = /@font-face\s*\{([^}]+)\}/g;
	let counter = 0;
	for (const match of css.matchAll(blockRe)) {
		const body = match[1];
		const family = body.match(/font-family:\s*['"]([^'"]+)['"]/)?.[1];
		const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
		const srcUrl = body.match(/src:\s*url\(([^)]+)\)/)?.[1];
		const unicodeRange = body.match(/unicode-range:\s*([^;]+)/)?.[1]?.trim() ?? "";
		if (!family || !weight || !srcUrl) continue;
		const slug = familySlug(family);
		// The Google CDN file basenames are stable hashes per (family, weight, subset).
		// Keep them as-is for traceability and idempotent re-downloads.
		const baseName = srcUrl.split("/").pop() ?? `font-${counter++}.woff2`;
		faces.push({
			family,
			weight,
			srcUrl,
			localPath: join(STATIC_FONTS, slug, `${weight}-${baseName}`),
			unicodeRange,
		});
	}
	return faces;
}

async function downloadOne(url: string, dest: string) {
	const res = await fetch(url, { headers: { "User-Agent": UA } });
	if (!res.ok) throw new Error(`fetch ${url}: ${res.status}`);
	const buf = new Uint8Array(await res.arrayBuffer());
	await mkdir(dirname(dest), { recursive: true });
	await writeFile(dest, buf);
}

function publicUrl(localPath: string): string {
	const idx = localPath.indexOf("/static/");
	return localPath.slice(idx + "/static".length);
}

function emitCss(faces: FontFace[]): string {
	const lines = [
		"/* Auto-generated by scripts/download-fonts.ts. Do not edit by hand. */",
		"/* JetBrains Mono and Noto Sans JP are licensed under SIL OFL 1.1. */",
		"/* See /fonts/<family>/OFL.txt for the full license text. */",
		"",
	];
	for (const f of faces) {
		lines.push("@font-face {");
		lines.push(`\tfont-family: '${f.family}';`);
		lines.push("\tfont-style: normal;");
		lines.push(`\tfont-weight: ${f.weight};`);
		lines.push("\tfont-display: swap;");
		lines.push(`\tsrc: url(${publicUrl(f.localPath)}) format('woff2');`);
		if (f.unicodeRange) lines.push(`\tunicode-range: ${f.unicodeRange};`);
		lines.push("}");
	}
	return `${lines.join("\n")}\n`;
}

async function main() {
	console.log("Fetching", GOOGLE_FONTS_URL);
	const cssRes = await fetch(GOOGLE_FONTS_URL, { headers: { "User-Agent": UA } });
	if (!cssRes.ok) throw new Error(`fetch CSS: ${cssRes.status}`);
	const css = await cssRes.text();

	const faces = parseFontFaces(css);
	console.log(`Parsed ${faces.length} @font-face blocks`);

	let done = 0;
	const concurrency = 8;
	const queue = [...faces];
	await Promise.all(
		Array.from({ length: concurrency }, async () => {
			while (queue.length) {
				const f = queue.shift();
				if (!f) return;
				await downloadOne(f.srcUrl, f.localPath);
				done++;
				if (done % 20 === 0) console.log(`  downloaded ${done}/${faces.length}`);
			}
		}),
	);
	console.log(`Downloaded ${done} files`);

	await writeFile(FONTS_CSS_OUT, emitCss(faces));
	console.log("Wrote", FONTS_CSS_OUT);
}

await main();
